#!/usr/bin/env bash
# Manage my process
start() {
	./manage_my_process &
	echo "$!" >/var/run/my_process.pid
	echo "manage_my_process started"
}

stop() {
	pid=$(cat /var/run/my_process.pid)
	kill "$pid"
	rm /var/run/my_process.pid
	echo "manage_my_process stopped"
}

restart() {
	pid=$(cat /var/run/my_process.pid)
	kill "$pid"
	rm /var/run/my_process.pid
	./manage_my_process &
	echo "$!" >/var/run/my_process.pid
	echo "manage_my_process restarted"
}
case "$1" in
start) start ;;
stop) stop ;;
restart) restart ;;
*)
	echo "Usage: manage_my_process {start|stop|restart}"
	;;
esac
